name: Qodana Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Qodana
        uses: JetBrains/qodana-action@v2023.1
        with:
          linter: jetbrains/qodana-jvm  # Substitua pelo linter adequado
